trying to fix no module named _config
cause 
  File "/home/apsage/.conda/envs/mb_aligner/lib/python3.8/site-packages/rh_config/__init__.py", line 1, in <module>
    from _config import config, get_entry
ModuleNotFoundError: No module named '_config'